export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const CATEGORYDATA = 'CATEGORYDATA';
export const ADDCATEGORY = 'ADDCATEGORY';
export const DELETECATEGORY = 'DELETECATEGORY';
export const UPDATECATEGORY = 'UPDATECATEGORY';